/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: "doc",
      id: 'intro',
      label: 'Welcome to BlockEden.xyz 👋'
    },
    {
      type: 'category',
      label: 'Aptos API 🌎 ',
      collapsible: false,
      items: [
        {
          type: "doc",
          id: 'aptos/index',
          label: 'Get started'
        },
        {
          type: "doc",
          id: 'aptos/aptos-data-analytics',
          label: 'Analytics and GraphQL'
        },
        {
          type: 'link',
          href: "/aptos-api-reference/get-ledger-info",
          label: "Aptos API Reference"
        }
      ],
    },
    {
      type: 'category',
      label: 'Sui API 💧 ',
      collapsible: false,
      items: [
        {
          type: "doc",
          id: 'sui/index',
          label: 'Get started'
        },
        {
          type: 'doc',
          id: 'sui/api-reference',
          label: "Sui API Reference"
        },
      ],
    },
    {
      type: "doc",
      id: 'compute-unit',
      label: 'Compute Unit'
    },
  ],
};

module.exports = sidebars;
